#!/usr/bin/env python3
"""
Rebuild training data (SFT, PPO prompts, probe) from existing trace logs.

This script processes logs that were previously generated by generate_training_data.py,
without re-running episodes. Useful for:
- Fixing data generation bugs without re-running expensive model inference
- Regenerating data with updated dataset_builder logic
- Testing data pipeline changes

Usage:
    python scripts/rebuild_data_from_logs.py qw14       # Rebuild from qw14 logs
    python scripts/rebuild_data_from_logs.py qw3        # Rebuild from qw3 logs
    python scripts/rebuild_data_from_logs.py qw14 --benign-only
    python scripts/rebuild_data_from_logs.py qw14 --shade-only
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import argparse
import json
from dataclasses import dataclass
from typing import List, Dict, Any, Optional

from src.training.dataset_builder import (
    Episode, build_sft_pairs, build_probe_text_items
)


@dataclass
class EpisodeResult:
    """Results from a single episode (matches generate_training_data.py format)."""
    episode_id: int
    success: bool
    num_steps: int
    include_secondary_task: bool
    main_task_success: Optional[bool]
    side_task_success: bool


def traj_to_episode(traj_path: Path, result: EpisodeResult) -> Episode:
    """Convert trajectory file to Episode format (from generate_training_data.py)."""
    steps = []
    for line in traj_path.read_text().splitlines():
        if not line.strip():
            continue
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        
        obs = d.get("observation", {})
        if isinstance(obs, dict):
            obs = obs.get("observation", "")
        
        steps.append({
            "step": d["step"],
            "events": [
                {"kind": "observation", "data": {"observation": obs if isinstance(obs, str) else json.dumps(obs)}, "step": d["step"]},
                {"kind": "action", "data": d.get("action", {}), "step": d["step"]},
            ]
        })
    
    # Add score event with proper labels
    if steps:
        # For probe training:
        # - side=1 when agent was given secondary task (regardless of success)
        # - side=0 when agent was NOT given secondary task (benign)
        side_label = 1 if result.include_secondary_task else 0
        main_label = int(result.main_task_success or 0)
        
        steps[-1]["events"].append({
            "kind": "score",
            "step": steps[-1]["step"],
            "data": {"main": main_label, "side": side_label}
        })
    
    return Episode(session_id=traj_path.stem, steps=steps)


def load_results(results_path: Path) -> Dict[int, EpisodeResult]:
    """Load results.jsonl file into a dict keyed by episode_id."""
    results = {}
    if not results_path.exists():
        return results
    
    for line in results_path.read_text().splitlines():
        if not line.strip():
            continue
        try:
            d = json.loads(line)
            result = EpisodeResult(
                episode_id=d["episode_id"],
                success=d.get("success", False),
                num_steps=d.get("num_steps", 0),
                include_secondary_task=d.get("include_secondary_task", False),
                main_task_success=d.get("main_task_success"),
                side_task_success=d.get("side_task_success", False),
            )
            results[result.episode_id] = result
        except (json.JSONDecodeError, KeyError):
            continue
    
    return results


def append_jsonl(path: Path, rows: List[Dict[str, Any]]) -> int:
    """Append rows to JSONL file."""
    if not rows:
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a" if path.exists() else "w") as f:
        f.writelines(json.dumps(r, ensure_ascii=False) + "\n" for r in rows)
    return len(rows)


def process_task_dir(
    task_dir: Path,
    sft_out: Optional[Path],
    ppo_out: Optional[Path],
    probe_out: Optional[Path],
) -> tuple:
    """Process a single task directory, returns (sft_n, ppo_n, probe_n)."""
    sft_n = ppo_n = probe_n = 0
    
    # Load results
    results_path = task_dir / "results.jsonl"
    results = load_results(results_path)
    
    if not results:
        return 0, 0, 0
    
    # Process each trajectory file
    for traj_file in sorted(task_dir.glob("trajectory_*.jsonl")):
        try:
            ep_id = int(traj_file.stem.split("_")[1])
        except (IndexError, ValueError):
            continue
        
        if ep_id not in results:
            continue
        
        result = results[ep_id]
        
        try:
            episode = traj_to_episode(traj_file, result)
        except Exception as e:
            print(f"    Warning: Failed to parse {traj_file.name}: {e}")
            continue
        
        if not episode.steps:
            continue
        
        # Build SFT pairs
        if sft_out is not None:
            sft_pairs = build_sft_pairs(episode)
            sft_n += append_jsonl(sft_out, [
                {"prompt": p.prompt, "response": p.response}
                for p in sft_pairs
            ])
        
        # Build PPO prompts
        if ppo_out is not None:
            if sft_out is None:
                sft_pairs = build_sft_pairs(episode)
            ppo_n += append_jsonl(ppo_out, [
                {"prompt": p.prompt}
                for p in sft_pairs
            ])
        
        # Build probe training data
        if probe_out is not None:
            probe_items = build_probe_text_items(episode, label_by_episode=False, window=5)
            probe_n += append_jsonl(probe_out, [
                {"text": p.text, "label": p.label}
                for p in probe_items
            ])
    
    return sft_n, ppo_n, probe_n


def rebuild_data(
    model_tag: str,
    include_benign: bool = True,
    include_shade: bool = True,
    output_dir: Path = None
):
    """Rebuild training data from existing trace logs."""
    
    if output_dir is None:
        output_dir = ROOT / "data"
    
    logs_dir = ROOT / "logs"
    benign_root = logs_dir / f"training_traces_{model_tag}_benign"
    shade_root = logs_dir / f"training_traces_{model_tag}_shade"
    
    # Check what exists
    trace_dirs = {}
    if include_benign and benign_root.exists():
        trace_dirs["benign"] = benign_root
    if include_shade and shade_root.exists():
        trace_dirs["shade"] = shade_root
    
    if not trace_dirs:
        print(f"ERROR: No trace directories found for model tag '{model_tag}'")
        print(f"Looking for:")
        print(f"  - {benign_root}")
        print(f"  - {shade_root}")
        sys.exit(1)
    
    # Count files
    print(f"Found trace directories:")
    for mode, path in trace_dirs.items():
        task_dirs = [d for d in path.iterdir() if d.is_dir()]
        n_files = sum(len(list(td.glob("trajectory_*.jsonl"))) for td in task_dirs)
        print(f"  {mode}: {path} ({len(task_dirs)} tasks, {n_files} trajectories)")
    print()
    
    # Output files
    sft_out = output_dir / f"sft_train_{model_tag}.jsonl"
    ppo_out = output_dir / f"ppo_prompts_{model_tag}.jsonl"
    probe_out = output_dir / f"probe_train_{model_tag}.jsonl"
    
    # Clear existing files
    for f in [sft_out, ppo_out, probe_out]:
        if f.exists():
            f.unlink()
    
    # Counters
    total_sft = total_ppo = total_probe = 0
    total_tasks = 0
    
    # Process each mode
    for mode, trace_root in trace_dirs.items():
        print(f"Processing {mode} episodes...")
        
        task_dirs = sorted([d for d in trace_root.iterdir() if d.is_dir()])
        
        for task_dir in task_dirs:
            sft_n, ppo_n, probe_n = process_task_dir(task_dir, sft_out, ppo_out, probe_out)
            
            if sft_n > 0 or ppo_n > 0 or probe_n > 0:
                total_tasks += 1
                total_sft += sft_n
                total_ppo += ppo_n
                total_probe += probe_n
                print(f"  {task_dir.name}: +{sft_n} SFT, +{ppo_n} PPO, +{probe_n} probe")
        
        print()
    
    # Summary
    print("=" * 60)
    print("Rebuild Summary")
    print("=" * 60)
    print(f"Total tasks processed: {total_tasks}")
    print(f"Output files:")
    print(f"  SFT:   {sft_out} ({total_sft} examples)")
    print(f"  PPO:   {ppo_out} ({total_ppo} prompts)")
    print(f"  Probe: {probe_out} ({total_probe} items)")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Rebuild training data from existing trace logs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/rebuild_data_from_logs.py qw14           # Rebuild from qw14 logs
    python scripts/rebuild_data_from_logs.py qw3            # Rebuild from qw3 logs
    python scripts/rebuild_data_from_logs.py qw14 --benign-only
    python scripts/rebuild_data_from_logs.py qw14 --shade-only
        """
    )
    parser.add_argument(
        "model_tag",
        help="Model tag (e.g., qw14, qw3, qw7, ll8)"
    )
    parser.add_argument(
        "--benign-only",
        action="store_true",
        help="Only process benign episodes"
    )
    parser.add_argument(
        "--shade-only",
        action="store_true",
        help="Only process shade episodes"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory (default: data/)"
    )
    
    args = parser.parse_args()
    
    include_benign = not args.shade_only
    include_shade = not args.benign_only
    
    rebuild_data(
        model_tag=args.model_tag,
        include_benign=include_benign,
        include_shade=include_shade,
        output_dir=args.output_dir
    )


if __name__ == "__main__":
    main()
